name: Check Markdown links

on:
  push:
    branches:
    - master
  schedule:
    # runs every monday at 9 am
    - cron: "0 9 * * 1"
    
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
